# Generated by Django 3.2.5 on 2021-08-02 06:42

import cotizacion_prestamo.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', cotizacion_prestamo.models.UnsignedAutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True, help_text='Date and time when the register was created')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Date and time when the register was updated')),
            ],
        ),
        migrations.CreateModel(
            name='LoanCapital',
            fields=[
                ('id', cotizacion_prestamo.models.UnsignedAutoField(primary_key=True, serialize=False, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=11)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=4)),
                ('created_on', models.DateTimeField(auto_now_add=True, help_text='Date and time when the register was created')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Date and time when the register was updated')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_loan_capital', to='cotizacion_prestamo.partner')),
            ],
        ),
    ]
